name: Run Cypress Tests

on:
  push:
    branches:
      - mentoring
  pull_request:
    branches:
      - mentoring

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress
        run: npx cypress run
